spring.profiles.active: develop
server:
  port: 8090
---
spring:
  jpa:
    show_sql: false
    database: H2
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
  h2.console.enabled: true
  config:
    activate:
      on-profile: develop
